---

version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_config:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - web

  dockergen:
    image: nginxproxy/docker-gen
    user: root
    command: -notify-sighup router -watch -wait 1s:5s /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    links:
      - router
    depends_on:
      - router
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - ./data/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certbot_config:/etc/letsencrypt
    networks:
      - web

  router:
    image: nginx:alpine
    container_name: router
    depends_on:
      - certbot
      - dockergen
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - certbot_config:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web

networks:
  web:

volumes:
# TODO : comment this
#   certbot_config: {}
#   certbot_www: {}
#   nginx_config: {}
  certbot_config:
    driver: local
    driver_opts:
      type:   none
      o:      bind
      device: ./data/certbot_config
  certbot_www:
    driver: local
    driver_opts:
      type:   none
      o:      bind
      device: ./data/certbot_www
  nginx_config:
    driver: local
    driver_opts:
      type:   none
      o:      bind
      device: ./data/nginx_config
